# Generated by Django 4.0.2 on 2024-07-31 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reciepts',
            new_name='receipt',
        ),
    ]
