# Generated by Django 4.0.2 on 2024-08-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0002_rename_reciepts_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='client_name',
            new_name='Client_Name',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='price',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='tip',
        ),
        migrations.AddField(
            model_name='receipt',
            name='Location',
            field=models.TextField(default='Michael'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='Role',
            field=models.TextField(default='Michael'),
            preserve_default=False,
        ),
    ]
