# Generated by Django 4.0.2 on 2024-08-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0003_rename_client_name_receipt_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='Salary',
            field=models.IntegerField(default=160000),
            preserve_default=False,
        ),
    ]
