# Generated by Django 4.0.2 on 2024-08-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0004_receipt_salary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Client_Name',
            new_name='Person_Name',
        ),
    ]
