# Generated by Django 4.0.2 on 2024-08-03 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0006_rename_location_receipt_city_rename_role_receipt_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
