# Generated by Django 4.0.2 on 2024-08-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0007_remove_chat_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='City',
            new_name='city_location',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Job',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Person_Name',
            new_name='person_name',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Salary',
            new_name='salary_money',
        ),
    ]
