# Generated by Django 4.0.2 on 2024-08-03 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0008_rename_city_receipt_city_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='city_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='job_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='person_name',
            new_name='profession',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='salary_money',
            new_name='salary',
        ),
    ]
