# Generated by Django 4.0.2 on 2024-08-04 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0010_rename_location_receipt_worklocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='name',
            new_name='Client_Name',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='worklocation',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='profession',
            new_name='Role',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='salary',
            new_name='Salary',
        ),
    ]
