# Generated by Django 4.0.2 on 2024-08-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0011_rename_name_receipt_client_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Role',
            new_name='Job',
        ),
    ]
