# Generated by Django 4.0.2 on 2024-08-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0012_rename_role_receipt_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Client_Name',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Salary',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='Job',
            new_name='profession',
        ),
    ]
