# Generated by Django 4.0.2 on 2024-08-05 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0016_alter_receipt_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Job',
            new_name='profession',
        ),
    ]
