# Generated by Django 4.0.2 on 2024-08-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0017_rename_job_receipt_profession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='Location',
            new_name='location',
        ),
    ]
