# Generated by Django 4.0.2 on 2024-08-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragoo', '0018_rename_location_receipt_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='phone',
            field=models.TextField(default='325-325'),
            preserve_default=False,
        ),
    ]
